server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${"DB_HOST}:3306/loggerdb
    username: ${"DB_USERNAME}
    password: ${"DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver